### ISSUE TITLE
Incompatibility with DelvUI

### ISSUE THREAD

**Issue by Will-ALVIDI** [skotlex/FFXIV_Material_UI#336]
Delv UI uses a strata level to manage the layering of HUD elements.
Everything they provide, even at the lowest level, seem to have a higher strata level than Material UI.

In short, when using both, all Delv UI HUD elements overlap Material UI HUD elements.

Have I missed something ? Is there a way to fix it ?

**Comment by ShichiIzanagi** [comment]
This is not a MUI issue, thats an IMGUI limitation, they cant render under the game UI without someone taking the time to make it happen, which no one did. Every plugin uses imgui hence why they always render over the game (many people wish it wasnt so but alas)

**Comment by Will-ALVIDI** [comment]
Thank you for your quick answer.

I opened an issue on the Delv UI repository and they gave me an answer directly after yours which seems to work : 
On Delv UI, go to Misc > Window Clipping and check Enabled.
