### ISSUE TITLE
Missing buttons on compass

### ISSUE THREAD

**Issue by unautrecompteBBT** [skotlex/FFXIV_Material_UI#37]
**Screenshots**

![image](https://user-images.githubusercontent.com/51453059/60772096-6f841380-a0f1-11e9-865f-0f9fec0350ec.png)

![image](https://user-images.githubusercontent.com/51453059/60772057-cd642b80-a0f0-11e9-823a-dc8b738f7b24.png)

**Describe the image**
On V1.0.0 Black (I didnt use the discord 1.1.4 version but the issue is visible on preview image), zoom and lock compass buttons are invisible.

**To Reproduce**
It's the compass (small map).

**Additional context**
(I dont know if it was the right place to write this)
(Thank u for ur work)

**Comment by skotlex** [comment]
I thought no one was using the button, so I deliberately excluded it to look neat, but it was my wrong judgment. I'll add it to this release. Thank you :>

**Comment by unautrecompteBBT** [comment]
Thank you :)

**Comment by skotlex** [comment]
The issue has not been resolved yet, so I will close after the operation.

**Comment by skotlex** [comment]
I hope you like this.

- **before**
![Untitled-1](https://user-images.githubusercontent.com/31692408/61063989-e5fb7b00-a43b-11e9-9458-56532ce3b071.jpg)

- **after**
![Untitled-2](https://user-images.githubusercontent.com/31692408/61064005-f01d7980-a43b-11e9-80a5-6576ba8e52ab.jpg)
